pipeline {
    // These are pre-build sections
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 10, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    
    // This is build section
    stages {
        stage('Init') {
            steps {
                script{
            
                        sh """
                            terraform init
                        """
                    }
                }
        
        }
        stage('Plan') {
            steps {
                script{
                    
                        sh """
                    
                            terraform plan
                        """
                    }
                }
        
        }
          stage('Deploy') {
             input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            } 
            
            steps {
                script{
                    
                        sh """
                        
                            terraform apply -auto-approve
                        """
                    
                }
            }
       

    post{
        always{
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}
    }
}